---

- name: job
  hosts: studydevops
  become: yes

  tasks:
  - name: change hostname
    lineinfile:
      dest=/etc/hostname
      regexp='^'
      state=absent
      line='mywebserv1'
      state=present

  - name: apt update
    apt: 
      update_cache=yes
  - name: Install git, mc, wget, curl, tree, docker, docker-compose
    apt:
      pkg:
        - git
        - mc
        - wget
        - curl
        - docker.io
        - docker-compose
        - tree
      state: present