---
- name: lesson1
  hosts: studydevops
  become: yes

  tasks:
  - name: change hostname
    lineinfile:
      dest=/etc/hostname
      regexp='^'
      state=absent
      line='mywebserv1'
      state=present

  tasks:
  - name: apt update
    apt: 
      update_cache=yes
  - name: Install git, mc, wget, curl, tree, docker, docker-compose
    apt:
      pkg:
      name: git
      state: present
      name: mc
      state: present
      name: wget
      state: present
      name: curl
      state: present
      name: docker.io
      state: present
      name: docker-compose
      state: present
      name: tree
      state: present

